name: Angular - Build

on:
  push:
    branches:
      - 'develop'
      - 'release-*'

jobs:
  build:
    name: Production Build
    runs-on: ubuntu-latest # [macOS-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run-script build-prod  # package.json -> "scripts"
    # - run: npm run-script test  # "ng test --no-watch --no-progress --browsers=ChromeHeadlessCI"
      - name: SonarCloud Scan
        if: success()
        uses: SonarSource/sonarcloud-github-action@v1.2 # file: sonar-project.properties
        env:
          GITHUB_TOKEN: ${{ secrets.GTOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARTOKEN }}
#      - name: Slack WebHook
#        if: failure()
#        uses: 8398a7/action-slack@v3
#        with:
#          status: ${{ job.status }}
#          fields: repo,author,commit,author,workflow,
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
