name: Heroku Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Heroku Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ost-yt" #Must be unique in Heroku
          heroku_email: "ilya.kab@gmail.com"
